QUALITY_CHECKLIST: dict[str, list[str]] = {
    "business_logic": [
        "domain_rules",
        "state_transitions",
        "calculation_accuracy",
        "data_integrity",
        "workflow_correctness",
    ],
    "adversarial": [
        "null_undefined_inputs",
        "empty_strings_arrays",
        "boundary_values",
        "type_coercion",
        "large_inputs",
        "race_conditions",
        "unicode_special_chars",
    ],
    "security": [
        "xss",
        "sql_injection",
        "command_injection",
        "code_injection",
        "csrf",
        "auth_bypass",
        "sensitive_data_exposure",
        "untrusted_input_sanitization",
        "open_redirects",
        "path_traversal",
    ],
    "performance": [
        "quadratic_algorithms",
        "heavy_sync_operations",
        "n_plus_1_queries",
        "large_imports",
        "redundant_computation",
    ],
    "memory": [
        "event_listener_cleanup",
        "subscription_timer_cleanup",
        "circular_references",
        "closure_retention",
    ],
    "error_handling": [
        "graceful_degradation",
        "user_error_messages",
    ],
    "accessibility": [
        "aria_attributes",
        "keyboard_navigation",
        "screen_reader",
        "focus_management",
    ],
    "seo": [
        "meta_tags",
        "semantic_html",
        "heading_hierarchy",
        "alt_text",
    ],
}
