from config import (
    TEST_APP_ID,
    TEST_INSTALLATION_ID,
    TEST_OWNER_ID,
    TEST_OWNER_NAME,
    TEST_REPO_ID,
    TEST_REPO_NAME,
    TEST_USER_ID,
    TEST_USER_NAME,
)
from services.github.github_types import GitHubEventPayload


deleted_payload: GitHubEventPayload = {
    "action": "deleted",
    "installation": {
        "id": TEST_INSTALLATION_ID,
        "account": {
            "login": TEST_OWNER_NAME,
            "id": TEST_OWNER_ID,
            "node_id": "O_kgDOB9UpXA",
            "avatar_url": "https://avatars.githubusercontent.com/u/-1?v=4",
            "gravatar_id": "",
            "url": f"https://api.github.com/users/{TEST_OWNER_NAME}",
            "html_url": f"https://github.com/{TEST_OWNER_NAME}",
            "followers_url": "https://api.github.com/users/installation-test/followers",
            "following_url": "https://api.github.com/users/installation-test/following{/other_user}",
            "gists_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/gists"
            + "{/gist_id}",
            "starred_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/starred"
            + "{/owner}{/repo}",
            "subscriptions_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/subscriptions",
            "organizations_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/orgs",
            "repos_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/repos",
            "events_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/events"
            + "{/privacy}",
            "received_events_url": f"https://api.github.com/users/{TEST_OWNER_NAME}/received_events",
            "type": "Organization",
            "site_admin": False,
        },
        "repository_selection": "selected",
        "access_tokens_url": f"https://api.github.com/app/installations/{TEST_INSTALLATION_ID}/access_tokens",
        "repositories_url": "https://api.github.com/installation/repositories",
        "html_url": f"https://github.com/organizations/{TEST_OWNER_NAME}/settings/installations/{TEST_INSTALLATION_ID}",
        "app_id": TEST_APP_ID,
        "app_slug": "issue-to-pull-request",
        "target_id": TEST_INSTALLATION_ID,
        "target_type": "Organization",
        "permissions": {
            "issues": "write",
            "contents": "write",
            "metadata": "read",
            "workflows": "write",
            "pull_requests": "write",
        },
        "events": [
            "commit_comment",
            "issues",
            "issue_comment",
            "label",
            "public",
            "pull_request",
            "pull_request_review",
            "pull_request_review_comment",
            "pull_request_review_thread",
        ],
        "created_at": "2024-03-21T19:09:38.000-07:00",
        "updated_at": "2024-03-21T19:09:38.000-07:00",
        "single_file_name": None,
        "has_multiple_single_files": False,
        "single_file_paths": [],
        "suspended_by": None,
        "suspended_at": None,
    },
    "repositories": [
        {
            "id": TEST_REPO_ID,
            "node_id": "R_kgDOJZc8Zg",
            "name": TEST_REPO_NAME,
            "full_name": f"{TEST_OWNER_NAME}/{TEST_REPO_NAME}",
            "private": True,
        }
    ],
    "sender": {
        "login": TEST_USER_NAME,
        "id": TEST_USER_ID,
        "node_id": "MDQ6VXNlcjY2Njk5Mjkw",
        "avatar_url": "https://avatars.githubusercontent.com/u/-1?v=4",
        "gravatar_id": "",
        "url": f"https://api.github.com/users/{TEST_USER_NAME}",
        "html_url": f"https://github.com/{TEST_USER_NAME}",
        "followers_url": f"https://api.github.com/users/{TEST_USER_NAME}/followers",
        "following_url": "https://api.github.com/users/username-test/following{/other_user}",
        "gists_url": "https://api.github.com/users/username-test/gists{/gist_id}",
        "starred_url": "https://api.github.com/users/username-test/starred{/owner}{/repo}",
        "subscriptions_url": "https://api.github.com/users/username-test/subscriptions",
        "organizations_url": "https://api.github.com/users/username-test/orgs",
        "repos_url": "https://api.github.com/users/username-test/repos",
        "events_url": "https://api.github.com/users/username-test/events{/privacy}",
        "received_events_url": "https://api.github.com/users/username-test/received_events",
        "type": "User",
        "site_admin": False,
    },
}
