AWSTemplateFormatVersion: '2010-09-09'
Description: 'Lambda monitoring - SNS notifications and CloudWatch alarm'

Parameters:
  Email:
    Type: String
    Description: Email address to receive notifications
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function to monitor

Resources:
  # SNS Topic for sending notifications
  ErrorNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: LambdaErrorNotificationTopic

  # SNS Subscription to send notifications to an email
  ErrorNotificationSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ErrorNotificationTopic
      Protocol: email
      Endpoint: !Ref Email

  # CloudWatch Alarm for Lambda function errors
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: LambdaFunctionErrorAlarm
      AlarmDescription: Alarm for Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
        - !Ref ErrorNotificationTopic
      Dimensions:
        - Name: FunctionName
          Value: !Ref LambdaFunctionName
