name: PyTest Workflow

on:
  push:
    branches:
      - '*'
      - '!main'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # https://github.com/actions/checkout

    - name: Set up Python 3.12
      uses: actions/setup-python@v5  # https://github.com/actions/setup-python
      with:
        python-version: "3.12"

    - name: Install pytest
      run: |
        pip install pytest pytest-cov pytest-asyncio
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

    - name: Run pytest
      env:  # https://github.com/gitautoai/gitauto/settings/secrets/actions
        GH_APP_ID: ${{ secrets.STAGE_GH_APP_ID }}
        GH_APP_NAME: ${{ secrets.GH_APP_NAME }}
        GH_APP_USER_ID: ${{ secrets.GH_APP_USER_ID }}
        GH_APP_USER_NAME: ${{ secrets.GH_APP_USER_NAME }}
        GH_PRIVATE_KEY: ${{ secrets.STAGE_GH_PRIVATE_KEY }}
        GH_WEBHOOK_SECRET: ${{ secrets.STAGE_GH_WEBHOOK_SECRET }}

        OPENAI_API_KEY: ${{ secrets.STAGE_OPENAI_API_KEY }}
        OPENAI_ORG_ID: ${{ secrets.STAGE_OPENAI_ORG_ID }}

        SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.STAGE_SUPABASE_SERVICE_ROLE_KEY }}
        SUPABASE_URL: ${{ secrets.STAGE_SUPABASE_URL }}

        STRIPE_API_KEY: ${{ secrets.STAGE_STRIPE_API_KEY }}
        STRIPE_FREE_TIER_PRICE_ID: ${{ secrets.STAGE_STRIPE_FREE_TIER_PRICE_ID }}
        STRIPE_PRODUCT_ID_FREE: ${{ secrets.STRIPE_PRODUCT_ID_FREE_STAGE }}
        STRIPE_PRODUCT_ID_STANDARD: ${{ secrets.STRIPE_PRODUCT_ID_STANDARD_STAGE }}
        
        ENV: stage
        PRODUCT_ID: ${{ secrets.STAGE_PRODUCT_ID }}
      run: python -m pytest --cov=./ --cov-report=xml
